---
# tasks file for vmtools

- name: assert supported distributions and versions
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version == '8' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version >= "7" )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version >= "31" )
        )

# KVM
- include: KVM.yml
  when: ansible_virtualization_type == "kvm"
